In [2]:
using Revise
include("model_fit_global.jl")
include("models.jl")
include("helper_functions.jl")
include("binning_helper_fs.jl")
using DataFrames


In [3]:
CD3_data = CSV.read("C:/Users/stravaglino3/Downloads/julia_code/CD3_data/dissociations.csv",DataFrame);

In [4]:
γϵ = delete_missing(CD3_data[:,2:3])
δϵ = delete_missing(CD3_data[:,8:9])
mix = delete_missing(CD3_data[:,14:15])
t_γϵ_thrml = delete_missing(CD3_data[:,5:5])
t_δϵ_thrml = delete_missing(CD3_data[:,11:11])
t_mix_thrml = delete_missing(CD3_data[:,17:17])
p_γϵ_thrml = survival_p.(t_γϵ_thrml)
p_δϵ_thrml = survival_p.(t_δϵ_thrml)
p_mix_thrml = survival_p.(t_mix_thrml);

In [5]:
plotly()
s1=scatter(γϵ[1],γϵ[2], title="γϵ")
s2=scatter(δϵ[1],δϵ[2], title="δϵ")
s3=scatter(mix[1],mix[2], title="mix")
display(plot(s1,s2,s3))
p1 = plot(t_γϵ_thrml,p2lnp(p_γϵ_thrml), label="γϵ")
plot!(t_δϵ_thrml,p2lnp(p_δϵ_thrml), label="δϵ")
plot!(t_mix_thrml,p2lnp(p_mix_thrml), label="mix")
title!("Thermal fluctuation dissociations")

<!DOCTYPE html>
 
 
 Plots.jl

┌ Info: For saving to png with the Plotly backend PlotlyBase has to be installed.
└ @ Plots C:\Users\stravaglino3\.julia\packages\Plots\lmp2A\src\backends.jl:372


<!DOCTYPE html>
 
 
 Plots.jl

## Thermal fluctuation bimolecular dissociation

### CD3γϵ

In [7]:
tspan = (0.0,10.0)
t = collect(0.0:0.1:10)

gr()

u₀ = [1.0]          # Initial condition
tspan = (0.0,10.0)  # Simulation interval
model_opt = (0.,100.)
pinit =[0.0]
dens = fill([],length(t_γϵ_thrml))
f_thrml = [[0.0]]
model = bimolecular_diss!

rates_γϵ_thrml,hes_γϵ_thrml,l_γϵ_thrml,boot_γϵ_thrml = optimization(model,p_γϵ_thrml,
                    dens,f_thrml,model_opt,t_γϵ_thrml)


loss_in(pinit) = 1.8708044753403916
Starting optimization with optimizer DiffEvoOpt{FitPopulation{Float64},RadiusLimitedSelector,BlackBoxOptim.AdaptiveDiffEvoRandBin{3},RandomBound{ContinuousRectSearchSpace}}
0.00 secs, 0 evals, 0 steps
0.50 secs, 666 evals, 566 steps, improv/step: 0.371 (last = 0.3710), fitness=0.033163894
1.01 secs, 1369 evals, 1269 steps, improv/step: 0.368 (last = 0.3656), fitness=0.033163791
1.51 secs, 2087 evals, 1988 steps, improv/step: 0.359 (last = 0.3421), fitness=0.033163791
2.02 secs, 2798 evals, 2699 steps, improv/step: 0.339 (last = 0.2855), fitness=0.033163791
2.53 secs, 3512 evals, 3413 steps, improv/step: 0.288 (last = 0.0938), fitness=0.033163791
3.03 secs, 4227 evals, 4128 steps, improv/step: 0.247 (last = 0.0490), fitness=0.033163791
3.53 secs, 4929 evals, 4830 steps, improv/step: 0.215 (last = 0.0285), fitness=0.033163791
4.04 secs, 5613 evals, 5519 steps, improv/step: 0.194 (last = 0.0464), fitness=0.033163791
4.54 secs, 6319 evals, 6358 steps, im

([7.41857232641849], Any[], 0.03316379073396449, Any[])

In [8]:
plotly()
p = rates_γϵ_thrml
k₋₁ᵒ = rates_γϵ_thrml
show_diss_fit(model,t_γϵ_thrml,p2lnp(p_γϵ_thrml),f_thrml)

<!DOCTYPE html>
 
 
 Plots.jl

## BFP data

micropipette = 2s
contact time = 0.2s

In [31]:
# Load Force-dependent bimolecular dissociation

f_γϵ, t_γϵ, γϵ_bin_ids = bin_dissociations(γϵ,6) #;bin_type="Force")
f_δϵ, t_δϵ, δϵ_bin_ids = bin_dissociations(δϵ,6)
f_mix, t_mix, mix_bin_ids = bin_dissociations(mix,6)
f_γϵ, t_γϵ = resort(f_γϵ, t_γϵ)
f_δϵ, t_δϵ = resort(f_δϵ, t_δϵ)
f_mix, t_mix = resort(f_mix, t_mix)
p_γϵ = survival_p.(t_γϵ)
p_δϵ = survival_p.(t_δϵ)
p_mix = survival_p.(t_mix)
return

### equal force spacing binning

In [32]:
s1=scatter(f_γϵ, t_γϵ, title="γϵ", legend=false)
s2=scatter(f_δϵ, t_δϵ, title="δϵ", legend=false)
s3=scatter(f_mix, t_mix, title="mix", legend=false)
display(plot(s1,s2,s3))

s1=scatter(t_γϵ, p2lnp(p_γϵ), title="γϵ")
s2=scatter(t_δϵ, p2lnp(p_δϵ), title="δϵ")
s3=scatter(t_mix, p2lnp(p_mix), title="mix")
plot(s1,s2,s3, legend = false)


<!DOCTYPE html>
 
 
 Plots.jl

<!DOCTYPE html>
 
 
 Plots.jl

In [33]:
p1 = plot_F_vs_t(f_γϵ,t_γϵ)
title!("γϵ")
p2 = plot_F_vs_t(f_δϵ,t_δϵ)
title!("δϵ")
p3 = plot_F_vs_t(f_mix,t_mix)
title!("mix")
plot(p1,p2,p3, legend = false,
                xlim = (0,Inf),
                ylim = (0,Inf))

<!DOCTYPE html>
 
 
 Plots.jl

In [34]:
# Load Force-dependent bimolecular dissociation

f_γϵ, t_γϵ, γϵ_bin_ids = bin_dissociations(γϵ,7;bin_type="equal number")
f_δϵ, t_δϵ, δϵ_bin_ids = bin_dissociations(δϵ,7;bin_type="equal number")
f_mix, t_mix, mix_bin_ids = bin_dissociations(mix,7;bin_type="equal number")
f_γϵ, t_γϵ = resort(f_γϵ, t_γϵ)
f_δϵ, t_δϵ = resort(f_δϵ, t_δϵ)
f_mix, t_mix = resort(f_mix, t_mix)
p_γϵ = survival_p.(t_γϵ)
p_δϵ = survival_p.(t_δϵ)
p_mix = survival_p.(t_mix)
return

### equally weighted bins (same # of pts per bin)

In [35]:
s1=scatter(f_γϵ, t_γϵ, title="γϵ",legend=false)
s2=scatter(f_δϵ, t_δϵ, title="δϵ",legend=false)
s3=scatter(f_mix, t_mix, title="mix",legend=false)
display(plot(s1,s2,s3))

s1=scatter(t_γϵ, p2lnp(p_γϵ), title="γϵ",legend=false)
s2=scatter(t_δϵ, p2lnp(p_δϵ), title="δϵ",legend=false)
s3=scatter(t_mix, p2lnp(p_mix), title="mix",legend=false)
plot(s1,s2,s3)

<!DOCTYPE html>
 
 
 Plots.jl

<!DOCTYPE html>
 
 
 Plots.jl

In [36]:
p1 = plot_F_vs_t(f_γϵ,t_γϵ)
title!("γϵ")
p2 = plot_F_vs_t(f_δϵ,t_δϵ)
title!("δϵ")
p3 = plot_F_vs_t(f_mix,t_mix)
title!("mix")
plot(p1,p2,p3, legend = false,
                xlim = (0,Inf),
                ylim = (0,Inf))


<!DOCTYPE html>
 
 
 Plots.jl

In [13]:
## try bimolecular dissociation bell model with activated state

u₀ = [1.0,0.0]
tspan = (0.0,15.0)
# model_opt = (-5.,3.)  # Simulation interval
model_opt = (0.,100.)
pinit = ones(8)
dens = fill([],length(t_γϵ))
t_γϵ_avg = mean.(t_γϵ)
f_γϵ_avg = mean.(f_γϵ)

model = bimolecular_diss_bell!
rates_γϵ,hes_γϵ,l_γϵ,boot_γϵ = optimization(model,p_γϵ,
                    dens,f_γϵ_avg,model_opt,t_γϵ)

loss_in(pinit) = 1.3176837250962063
Starting optimization with optimizer DiffEvoOpt{FitPopulation{Float64},RadiusLimitedSelector,BlackBoxOptim.AdaptiveDiffEvoRandBin{3},RandomBound{ContinuousRectSearchSpace}}
0.00 secs, 0 evals, 0 steps
0.50 secs, 236 evals, 186 steps, improv/step: 1.000 (last = 1.0000), fitness=Inf
1.00 secs, 478 evals, 428 steps, improv/step: 1.000 (last = 1.0000), fitness=Inf
1.51 secs, 714 evals, 664 steps, improv/step: 1.000 (last = 1.0000), fitness=Inf
2.01 secs, 950 evals, 900 steps, improv/step: 1.000 (last = 1.0000), fitness=Inf
2.51 secs, 1198 evals, 1148 steps, improv/step: 0.997 (last = 0.9879), fitness=1.447016849
3.01 secs, 1432 evals, 1382 steps, improv/step: 0.993 (last = 0.9701), fitness=1.447016849
3.51 secs, 1676 evals, 1626 steps, improv/step: 0.993 (last = 0.9918), fitness=1.447016849
4.01 secs, 1911 evals, 1861 steps, improv/step: 0.990 (last = 0.9702), fitness=1.442830067
4.52 secs, 2155 evals, 2105 steps, improv/step: 0.985 (last = 0.9467), fitn

87.97 secs, 26203 evals, 26153 steps, improv/step: 0.326 (last = 0.2011), fitness=0.160650986
88.48 secs, 26379 evals, 26329 steps, improv/step: 0.325 (last = 0.1420), fitness=0.160650986
88.98 secs, 26552 evals, 26502 steps, improv/step: 0.324 (last = 0.1445), fitness=0.160621707
89.48 secs, 26722 evals, 26672 steps, improv/step: 0.322 (last = 0.1059), fitness=0.160621707
89.99 secs, 26899 evals, 26849 steps, improv/step: 0.321 (last = 0.0791), fitness=0.160603908
90.50 secs, 27079 evals, 27029 steps, improv/step: 0.320 (last = 0.1222), fitness=0.160582221
91.00 secs, 27249 evals, 27199 steps, improv/step: 0.319 (last = 0.1647), fitness=0.160535939
91.50 secs, 27420 evals, 27370 steps, improv/step: 0.318 (last = 0.1754), fitness=0.160535939
92.00 secs, 27591 evals, 27541 steps, improv/step: 0.317 (last = 0.2047), fitness=0.160461394
92.50 secs, 27764 evals, 27714 steps, improv/step: 0.316 (last = 0.1329), fitness=0.160454483
93.01 secs, 27932 evals, 27882 steps, improv/step: 0.315 (la

([4.137718576451779, 1.8390749324865377e-22, 0.044801390224956494, 0.24161553467546298, 0.3419167462713642, 1.8006439078705896e-22, 12.746290845265438, 3.546836101527082], Any[], 0.1597991026273562, Any[])

In [14]:
display(mean.(t_γϵ_thrml))
display(mean.(t_δϵ_thrml))
display(mean.(t_mix_thrml))

1-element Array{Float64,1}:
 0.13496072794117644

1-element Array{Float64,1}:
 0.13966825000000002

1-element Array{Float64,1}:
 0.40650847457627115

In [15]:
p = rates_γϵ
p1 = show_diss_fit(model, t_γϵ, p2lnp(p_γϵ), f_γϵ_avg)
display(p1)
Fs = collect(0.:0.5:30.)

plot_F_vs_t(f_γϵ,t_γϵ)
plot_force_lifetime_fit(model,Fs,f_γϵ,t_γϵ)

<!DOCTYPE html>
 
 
 Plots.jl

<!DOCTYPE html>
 
 
 Plots.jl